export const CREATE_APP_REQUEST = 'CREATE_APP_REQUEST';
export const CREATE_APP_SUCCESS = 'CREATE_APP_SUCCESS';
export const CREATE_APP_FAILURE = 'CREATE_APP_FAILURE';

export const GET_APP_REQUEST = 'GET_APP_REQUEST';
export const GET_APP_SUCCESS = 'GET_APP_SUCCESS';
export const GET_APP_FAILURE = 'GET_APP_FAILURE';

export const UPDATE_APP_REQUEST = 'UPDATE_APP_REQUEST';
export const UPDATE_APP_SUCCESS = 'UPDATE_APP_SUCCESS';
export const UPDATE_APP_FAILURE = 'UPDATE_APP_FAILURE';
